apiVersion: v1
kind: Service
metadata:
  name: yolo-graviton-large
  namespace: yolo
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: grpc
    port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    app: yolo-inference