apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"prometheus.io/path":"/metrics","prometheus.io/port":"8002","prometheus.io/scrape":"true"},"labels":{"app":"model-inference"},"name":"resnet50-graviton-med","namespace":"resnet50"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"model-inference"}},"template":{"metadata":{"labels":{"app":"model-inference"}},"spec":{"containers":[{"args":["--model-repository=octoml/models","--strict-model-config=false"],"command":["tritonserver"],"image":"89937409924.dkr.ecr.us-east-1.amazonaws.com/resnet50:c7g.8xlarge","name":"model-inference","ports":[{"containerPort":8001,"protocol":"TCP"},{"containerPort":8000,"protocol":"TCP"}]}],"imagePullSecrets":[{"name":"regcred"}],"nodeSelector":{"node.kubernetes.io/instance-type":"c7g.4xlarge"},"tolerations":[]}}}}
    prometheus.io/path: /metrics
    prometheus.io/port: "8002"
    prometheus.io/scrape: "true"
  creationTimestamp: "2022-08-28T17:05:34Z"
  generation: 2
  labels:
    app: model-inference
  name: resnet50-graviton-med
  namespace: resnet50
  resourceVersion: "173648"
  uid: 7f99c28c-b413-417e-b7ee-10104be935db
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: model-inference
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: model-inference
    spec:
      containers:
      - args:
        - --model-repository=octoml/models
        - --strict-model-config=false
        command:
        - tritonserver
        image: 89937409924.dkr.ecr.us-east-1.amazonaws.com/resnet50:c7g.4xlarge
        imagePullPolicy: IfNotPresent
        name: model-inference
        ports:
        - containerPort: 8001
          protocol: TCP
        - containerPort: 8000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: regcred
      nodeSelector:
        node.kubernetes.io/instance-type: c7g.4xlarge
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2022-08-28T17:05:34Z"
    lastUpdateTime: "2022-08-28T17:05:34Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2022-08-28T17:05:34Z"
    lastUpdateTime: "2022-08-28T17:12:39Z"
    message: ReplicaSet "resnet50-graviton-med-5b75d5b755" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 2
  replicas: 2
  unavailableReplicas: 2
  updatedReplicas: 2
